20111210
========

- :class:`lino.modlib.links.models.LinksFromThis`.column_names
- removed contacts.RoleType and contacts.Role and adapted demo and std fixtures
- Adapted :func:`lino.apps.dsbe.migrate.migrate_from_1_2_8`

- Note that :class:`lino.apps.dsbe.models.ContactPersons`
  inherits :class:`lino.modlib.links.models.LinksFromThis`
  just to override the label.

Discovered that due to a bug in previous dpy versions
there were some Upload records on Role and RoleType 
in a customer's database.



    for so in expand(o):
  File "/var/snapshots/lino/lino/utils/dpy.py", line 358, in expand
    for o in obj:
  File "/usr/local/django/dsbe_eupen/fixtures/d20111208.py", line 15985, in contacts_person_objects
    yield create_contacts_person(6066,u'1971-08-05',u'Monique Hubertine',u'Ganser',u'Frau','F',True,80,u'CREGBEBB:BE1373
2000852439',u'',u'',u'GAMO710805',True,False,1,date(2010,11,3),date(2011,9,30),200085,200085,u'Eupen',None,u'',u'710805
086-50',199137,None,u'BE',u'590678199976',None,None,u'',u'',u'',None,None,None,False,False,None,2,False,False,False,Fals
e,False,False,None,u'Art. 60\xa77',u'',u'',u'',14)
  File "/usr/local/django/dsbe_eupen/fixtures/d20111208.py", line 135, in create_contacts_person
    return insert_child(contacts_Contact.objects.get(pk=contact_ptr_id),contacts_Person,birth_date=birth_date,first_name
=first_name,last_name=last_name,title=title,gender=gender,is_active=is_active,activity_id=activity_id,bank_account1=bank
_account1,bank_account2=bank_account2,remarks2=remarks2,gesdos_id=gesdos_id,is_cpas=is_cpas,is_senior=is_senior,group_id
=group_id,coached_from=coached_from,coached_until=coached_until,coach1_id=coach1_id,coach2_id=coach2_id,birth_place=birt
h_place,birth_country_id=birth_country_id,civil_state=civil_state,national_id=national_id,health_insurance_id=health_ins
urance_id,pharmacy_id=pharmacy_id,nationality_id=nationality_id,card_number=card_number,card_valid_from=card_valid_from,
card_valid_until=card_valid_until,card_type=card_type,card_issuer=card_issuer,noble_condition=noble_condition,residence_
type=residence_type,in_belgium_since=in_belgium_since,unemployed_since=unemployed_since,needs_residence_permit=needs_res
idence_permit,needs_work_permit=needs_work_permit,work_permit_suspended_until=work_permit_suspended_until,aid_type_id=ai
d_type_id,income_ag=income_ag,income_wg=income_wg,income_kg=income_kg,income_rente=income_rente,income_misc=income_misc,
is_seeking=is_seeking,unavailable_until=unavailable_until,unavailable_why=unavailable_why,obstacles=obstacles,skills=ski
lls,job_agents=job_agents,job_office_contact_id=job_office_contact_id)
  File "/var/snapshots/lino/lino/utils/mti.py", line 145, in insert_child
    new_obj.save()
  File "/var/snapshots/lino/lino/apps/dsbe/models.py", line 531, in save
    if self.job_office_contact.b == self:
  File "/var/snapshots/lino/lino/fields.py", line 320, in __get__
    rel_obj = ct.get_object_for_this_type(pk=pk)
  File "/var/snapshots/django/django/contrib/contenttypes/models.py", line 114, in get_object_for_this_type
    return self.model_class()._base_manager.using(self._state.db).get(**kwargs)
  File "/var/snapshots/django/django/db/models/query.py", line 361, in get
    % self.model._meta.object_name)
DoesNotExist: Person matching query does not exist.
